/**
 * Palette — Single source of truth for colour values
 *
 * Used by:
 * - opengraph-image.tsx (server-side, can't read CSS vars)
 * - Any server component needing colour values
 *
 * Generated by: scripts/generate-palette.mjs
 * CSS tokens in: src/styles/colour-tokens.css (keep in sync)
 */

export const palette = {
  primary: { oklch: "oklch(55% 0.15 220)", hex: "#0083ad" },
  primaryLight: { oklch: "oklch(70% 0.15 220)", hex: "#00b2de" },
  primaryMuted: { oklch: "oklch(45% 0.07 220)", hex: "#145f72" },
  accent: { oklch: "oklch(72% 0.12 175)", hex: "#39bda0" },
  accentMuted: { oklch: "oklch(52% 0.07 175)", hex: "#357766" },
  surface1: { oklch: "oklch(11% 0.01 220)", hex: "#020506" },
  surface2: { oklch: "oklch(15% 0.01 220)", hex: "#050d10" },
  surface3: { oklch: "oklch(23% 0.02 220)", hex: "#121f23" },
  surface4: { oklch: "oklch(29% 0.03 220)", hex: "#1d2e34" },
  textPrimary: { oklch: "oklch(95% 0.005 220)", hex: "#ebeff1" },
  textSecondary: { oklch: "oklch(75% 0.02 220)", hex: "#a1b1b7" },
  textMuted: { oklch: "oklch(55% 0.02 220)", hex: "#65757a" },
} as const;

/** OG image gradients — hex/rgba for Satori compatibility */
export const ogGradients = {
  background: "linear-gradient(150deg, #020506 0%, #050d10 50%, #121f23 100%)",
  glow: "radial-gradient(circle, rgba(0,131,173,0.2) 0%, transparent 60%)",
  accentText: "rgba(57,189,160,0.9)",
  gridLine: "rgba(0,131,173,0.08)",
} as const;

export type PaletteToken = keyof typeof palette;